version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:14.15"
    steps:
      # install node and checkout code
      - node/install:
          node-version: '14.15'         
      - checkout
      # Use root level package.json to install dependencies in the frontend app
    - run:
          name: Install Front-End
          command: npm run install:frontend
      - run:
          name: Install Back-end
          command: npm run install:backend
      - run:
          name: Build Front-End
          command: npm run build:frontend
      - run:
          name: Build Back-end
          command: npm run build:backend
      - run:
          name: Deploy Front-End
          command: npm run deploy:frontend
      - run:
          name: Deploy Back-end
          command: npm run deploy:backend
  deploy:
    docker:
      - image: "cimg/base:stable"
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: '14.15' 
      - eb/setup
      - aws-cli/setup
      - aws-cli/install
      - aws-cli/setup:
           aws-access-key-id: AWS_ACCESS_KEY_ID
           aws-region: AWS_DEFAULT_REGION
           aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - checkout
      - run:
          name: Deploy App
          # TODO: Install, build, deploy in both apps
          command: npm run deploy
           
            
workflows:
    build-deploy:
      jobs:
        - build:
            filters:
              branches:
                only: 
                  - master